### ISSUE TITLE
Still in work?

### ISSUE THREAD

**Issue by grimmreefer** [mythgarr/Spriter2Unity#11]
Hello, first of all, Spriter2Unity is a great tool and a big help for me and my games. Sadly there are a few issues inside.

All cases appears randomly

- some Sprites disappear and i need to fix it in the Animation Window
- the Scale isnt the same as in Spriter2D after import the Spriter Project Folder
- the Sprites "jumps" around while the Animation is running
- No animations available after import the Spriter Project Folder

Thats all so far.

I know this Tool is for free and you dont get Money from it, but i realy hope you still work on it because as i said, its a great tool.

If you dont, please let us know, so we can look for an alternative Plugin. 

Have a nice Day.

**Comment by mythgarr** [comment]
I stopped active development on Spriter2Unity about a year ago. There is some active development in several of the forks, you might want to check there to see if anybody has fixed your issues.
