### ISSUE TITLE
Unity 5 Compatibility issue

### ISSUE THREAD

**Issue by alaa-eddine** [mythgarr/Spriter2Unity#12]
Hello,

Just tried to migrate my project to Unity 5 and noticed that Spriter2Unity is not compatible.
the error message is 

```
Assets/ThirdParty/Spriter2Unity/Editor/Unity/AnimationBuilder.cs(106,30): error CS0619: `UnityEditor.AnimationUtility.SetAnimationType(UnityEngine.AnimationClip, UnityEditor.ModelImporterAnimationType)' is obsolete: `SetAnimationType is no longer supported'

```
I tried to debug it and found that Spriter2Unity use two obsolete function

AnimationBuilder line 104
AnimationUtility.SetAnimationType(animClip, ModelImporterAnimationType.Generic);

and 

ScmlPostProcessor line 126 
UnityEditor.Animations.AnimatorController.AddAnimationClipToController(controller, animationClip);

Can you fix it please :) ?

**Comment by alaa-eddine** [comment]
managed to get it working, and sent a PR here :) 

https://github.com/mythgarr/Spriter2Unity/pull/13

Tested on Unity5 RC2
Hope it'll help

**Comment by tim-tim** [comment]
confirmed, works for me on Unity 5.0.0f4 but there is still one warning:

Assets/ThirdParty/Spriter2Unity/Editor/Utils/AnimationCurveUtils.cs(192,26): warning CS0219: The variable `bindingFlags' is assigned but its value is never used

is that vital?

**Comment by AlexanderYoshi** [comment]
You can remove that line if you want safely, tim-tim.

**Comment by dschutten** [comment]
It looks like no one's done a build of the unity package file itself in the Package folder. Is there an easy way to do that? I'm just an art guy. :)

**Comment by mwillson** [comment]
Bumping thread, hoping for some response on dschutten's concern. If there's no reply here soon, I will personally message the owner of this fork. I could, but I really don't want to fork it and do it myself, no sense in having soo many versions of this project out there.

**Comment by Xelnath** [comment]
I have ceased working on this project to go work using the Spine program. Its features and technology are well worth the meager cost in price over Spriter. Wish you all the best.

**Comment by mythgarr** [comment]
Due to a conflict of interests I have been unable to develop this project since early last year. Several other engineers have created forks, a few have submitted pull requests to get their fixes/enhancements back into this version. 
I'm happy to review & merge any pull requests I receive but cannot directly participate in writing code on this project.
